name: Deploy to Internal IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o publish_output

      - name: Stop IIS site
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "Test-CICDJnekins"
          Stop-Website -Name "Test-CICDJnekins"
        shell: powershell

      - name: Deploy to IIS folder
        run: |
          Remove-Item -Recurse -Force "C:\Users\javad\source\repos\Test-CICDJnekins-publish\*" 
          Copy-Item -Path "publish_output\*" -Destination "C:\Users\javad\source\repos\Test-CICDJnekins-publish" -Recurse
        shell: powershell

      - name: Start IIS site
        run: |
          Start-WebAppPool -Name "Test-CICDJnekins"
          Start-Website -Name "Test-CICDJnekins"
        shell: powershell
